language: python
sudo: false
python:
  - "2.7"
  - "3.6"
  - "3.7-dev"
  - "pypy"
  - "pypy-5.3.1"

matrix:
    allow_failures:
        - python: 3.7-dev
        - python: pypy
        - python: pypy-5.3.1


install:
  - pip install pipenv

script:
  - pipenv install --dev --skip-lock
  - pipenv run make tests
